" An example for a vimrc file.
"
" Maintainer:	The Vim Project <https://github.com/vim/vim>
" Last Change:	2023 Aug 10
" Former Maintainer:	Bram Moolenaar <Bram@vim.org>
"
" To use it, copy it to
"	       for Unix:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"	 for MS-Windows:  $VIM\_vimrc
"	      for Haiku:  ~/config/settings/vim/vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

" Make line numbers visible
set number

" Highlight current line
set cursorline

" Enable mouse support
set mouse=a

" Show matching brackets when cursor is over one
set showmatch

" Enable syntax highlighting
syntax on

" Indentation settings (adjust to your preference)
set tabstop=2       " number of spaces a <Tab> counts for
set shiftwidth=2    " number of spaces used for autoindent
set expandtab       " convert tabs to spaces
set smartindent     " smart autoindenting on new lines

" Better search
set ignorecase      " case-insensitive search...
set smartcase       " ...unless uppercase letters are used
set incsearch       " show matches as you type
set hlsearch        " highlight matches

" Make backspace behave like most editors
set backspace=indent,eol,start

" Enable line wrapping
set wrap

" Display line and column number in status line
set ruler

" Show line/column even in command mode
set laststatus=2

" Allow hidden buffers (keep unsaved files open in background)
set hidden

" Visual bell instead of beeping
set visualbell

" Enable system clipboard (if your Vim was compiled with +clipboard)
set clipboard=unnamedplus
